# Generated by Django 5.0.6 on 2025-03-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=100)),
                ('taskDescription', models.TextField(max_length=100)),
                ('is_Completed', models.BooleanField(default=False)),
                ('taskAssignDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
